name: Push

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  PROJECT_NAME: retrospective
  PROJECT_DIR: retrospective
  VERSION_FILE: retrospective/version.py
  DEFAULT_BRANCH: master
  BOT_NAME: fragile-bot
  BOT_EMAIL: bot@fragile.tech
  BOT_AUTH_TOKEN: ${{ secrets.BOT_AUTH_TOKEN }}
  TEST_PYPI_PASS: ${{ secrets.TEST_PYPI_PASS }}
  PYPI_PASS: ${{ secrets.PYPI_PASS }}
  DOCKER_ORG: guillemdb
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_LOGIN }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASS }}
  PIP_CACHE: |
    ~/.cache/pip
    ~/.local/bin
    ~/.local/lib/python3.*/site-packages

jobs:
  style-check:
    name: Style check
    if: "!contains(github.event.head_commit.message, 'Bump version')"
    runs-on: ubuntu-20.04
    steps:
    - name: actions/checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: actions/cache
      uses: actions/cache@v2
      with:
        path: ${{ env.PIP_CACHE }}
        key: ubuntu-20.04-pip-lint-${{ hashFiles('requirements-lint.txt') }}
        restore-keys: ubuntu-20.04-pip-lint-
    - name: Install lint dependencies
      run: |
        set -x
        pip install -r requirements-lint.txt

    - name: Run style check and linter
      run: |
        set -x
        make check

  bump-version:
    name: Bump package version
    if: "!contains(github.event.head_commit.message, 'Bump version') && github.ref == 'refs/heads/main' && '$BOT_AUTH_TOKEN' != ''"
    runs-on: ubuntu-20.04
    steps:
      - name: actions/checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 100
      - name: current_version
        run: |
          set -x
          echo "current_version=$(grep __version__ $VERSION_FILE | cut -d\" -f2)" >> $GITHUB_ENV
          echo "version_file=$VERSION_FILE" >> $GITHUB_ENV
          echo 'bot_name="${BOT_NAME}"' >> $GITHUB_ENV
          echo 'bot_email="${BOT_EMAIL}"' >> $GITHUB_ENV
      - name: FragileTech/bump-version
        uses: FragileTech/bump-version@main
        with:
          current_version: "${{ env.current_version }}"
          files: "${{ env.version_file }}"
          commit_name: "${{ env.bot_name }}"
          commit_email: "${{ env.bot_email }}"
          login: "${{ env.bot_name }}"
          token: "${{ secrets.BOT_AUTH_TOKEN }}"
